/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Prop.Presentacion;

import Prop.Dominio.DocumentKey;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JScrollPane;

/**
 *
 * @author JOAN
 */
public class ListaAutores extends javax.swing.JFrame {

    private ControladorPresentacion ctrlP;
    /**
     * Creates new form ListaAutores
     */
    public ListaAutores() {
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        initComponents();
        ctrlP = ControladorPresentacion.getInstance();
        ArrayList<String> la = ctrlP.listarAutoresPrefijo("");
        this.updateAutores(la);
        this.updateTitulos(new ArrayList<>());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane1.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
        prefixBuscado = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaAutores = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaTitulos = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setEnabled(false);

        prefixBuscado.setToolTipText("Inserte el autor aquí");
        prefixBuscado.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        prefixBuscado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                prefixBuscadoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                prefixBuscadoKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(prefixBuscado);

        listaAutores.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Autor1", "Autor2", "Autor3", "..." };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaAutores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaAutoresMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listaAutores);

        listaTitulos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Título1", "Título2", "Título3", "..." };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaTitulos.setFocusable(false);
        jScrollPane3.setViewportView(listaTitulos);

        jButton1.setBackground(new java.awt.Color(255, 102, 102));
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Salir");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Prop/Presentacion/Images/Lupa (2).png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel2.setText("Títulos:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(103, 103, 103))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void prefixBuscadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prefixBuscadoKeyTyped
        ctrlP = ControladorPresentacion.getInstance();
        String prefijo = prefixBuscado.getText();
        ArrayList<String> lista = ctrlP.listarAutoresPrefijo(prefijo);
        this.updateAutores(lista);
    }//GEN-LAST:event_prefixBuscadoKeyTyped

    private void listaAutoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaAutoresMouseClicked
        ctrlP = ControladorPresentacion.getInstance();
        
        String elegido = listaAutores.getSelectedValue();
        ArrayList<String> titulos = ctrlP.listaTitulosAutor(elegido);
                
        this.updateTitulos(titulos);
    }//GEN-LAST:event_listaAutoresMouseClicked

    private void prefixBuscadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prefixBuscadoKeyReleased
        ctrlP = ControladorPresentacion.getInstance();
        String prefijo = prefixBuscado.getText();
        ArrayList<String> lista = ctrlP.listarAutoresPrefijo(prefijo);
        this.updateAutores(lista);
    }//GEN-LAST:event_prefixBuscadoKeyReleased

    private void updateAutores(ArrayList<String> la) {
        DefaultListModel modelo = new DefaultListModel();
        for (String s:
             la) {
             modelo.addElement(s);
        }
        this.listaAutores.setModel(modelo);
        this.updateTitulos(new ArrayList<>());
    }
    
    private void updateTitulos(ArrayList<String> lt) {
        DefaultListModel modelo = new DefaultListModel();
        for (String e:
             lt) {
             modelo.addElement(e);
        }
        this.listaTitulos.setModel(modelo);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaAutores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaAutores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaAutores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaAutores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaAutores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listaAutores;
    private javax.swing.JList<String> listaTitulos;
    private javax.swing.JTextPane prefixBuscado;
    // End of variables declaration//GEN-END:variables
}
